name: docker build test

on: 
  workflow_call:
  pull_request:
  push:
    branches: [main, develop]

permissions:
  actions: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: build docker
        uses: docker/build-push-action@v7
        with:
          context: .
          file: .Dockerfile
          tags: test:latest
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max